### PR TITLE
Feat/shadow dom

### PR DESCRIPTION
**Pull request by thepassle**
This PR could do with some more shadow DOM related tests, but at least all existing tests pass

### CODE REVIEW

**Comment by thepassle** [comment]
Updated the PR, thanks @konnorrogers (can't tag you) for the deep query selector impl 😄

**Comment by koddsson** [comment]
This is great!

**Comment by koddsson** [comment]
I'm so confused why that one test is just failing on chromium 🤔

**Comment by thepassle** [comment]
Huh thats weird, tests were passing locally. Ill try to take a look at it today if i have time

**Comment by koddsson** [comment]
Ooooooh, I think this is failing because it's trying to report code coverage and it's blocking that execution since you're a "untrusted" user to this repo.

**Comment by koddsson** [comment]
> Ooooooh, I think this is failing because it's trying to report code coverage and it's blocking that execution since you're a "untrusted" user to this repo.

Can't be asked to fix this now.

**Pull request merged**
